-- Tabela de Auditoria para Formulários
-- Registra todas as alterações com histórico completo
CREATE TABLE FORMULARIOS_AUDITORIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FORMULARIO_PK NUMBER NOT NULL,
    ACAO VARCHAR2(20) NOT NULL CHECK (ACAO IN ('CRIACAO', 'EDICAO', 'EXCLUSAO')),
    USUARIO_ID NUMBER NOT NULL,
    USUARIO_NOME VARCHAR2(200) NOT NULL,
    USUARIO_PERFIL VARCHAR2(20) NOT NULL,
    DATA_HORA TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    IP VARCHAR2(45),
    USER_AGENT VARCHAR2(500),
    PAYLOAD_ANTES CLOB,
    PAYLOAD_DEPOIS CLOB,
    CONSTRAINT FK_FORMULARIOS_AUDITORIA_FORMULARIO FOREIGN KEY (FORMULARIO_PK) REFERENCES FORMULARIOS(PK)
);

-- Índices para performance e consultas
CREATE INDEX IDX_FORM_AUDITORIA_FORMULARIO ON FORMULARIOS_AUDITORIA(FORMULARIO_PK);
CREATE INDEX IDX_FORM_AUDITORIA_USUARIO ON FORMULARIOS_AUDITORIA(USUARIO_ID);
CREATE INDEX IDX_FORM_AUDITORIA_DATA ON FORMULARIOS_AUDITORIA(DATA_HORA);
CREATE INDEX IDX_FORM_AUDITORIA_ACAO ON FORMULARIOS_AUDITORIA(ACAO);

-- Trigger automático para auditoria em todas as operações
CREATE OR REPLACE TRIGGER TRG_FORMULARIOS_AUDITORIA
    BEFORE INSERT OR UPDATE OR DELETE ON FORMULARIOS
    FOR EACH ROW
DECLARE
    v_acao VARCHAR2(20);
    v_usuario_id NUMBER;
    v_usuario_nome VARCHAR2(200);
    v_usuario_perfil VARCHAR2(20);
    v_ip VARCHAR2(45);
    v_user_agent VARCHAR2(500);
    v_payload_antes CLOB;
    v_payload_depois CLOB;
BEGIN
    -- Determina ação
    IF INSERTING THEN
        v_acao := 'CRIACAO';
    ELSIF UPDATING THEN
        v_acao := 'EDICAO';
    ELSE
        v_acao := 'EXCLUSAO';
    END IF;

-- Tabela de Auditoria para Formulários
-- Registra todas as alterações com histórico completo
CREATE TABLE FORMULARIOS_AUDITORIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FORMULARIO_PK NUMBER NOT NULL,
    ACAO VARCHAR2(20) NOT NULL CHECK (ACAO IN ('CRIACAO', 'EDICAO', 'EXCLUSAO')),
    USUARIO_ID NUMBER NOT NULL,
    USUARIO_NOME VARCHAR2(200) NOT NULL,
    USUARIO_PERFIL VARCHAR2(20) NOT NULL,
